-- =============================================================================
-- Seed: Global Exercise Catalog (97 exercises)
-- Source: plantilla-estatica/semilla.txt
-- Run with: psql or Supabase SQL Editor (use Service Role Key)
-- =============================================================================

INSERT INTO public.global_exercises (nombre, grupo_muscular, parent_id, equipo, variaciones) VALUES
  ('Press de Banca Plano', 'Pecho (Pectorales)', NULL, 'Barra / Mancuernas', 'Agarre cerrado (enfocado en tríceps), agarre ancho, con pausa.'),
  ('Press Inclinado', 'Pecho (Pectorales)', NULL, 'Barra / Mancuernas / Máquina Smith', NULL),
  ('Press Declinado', 'Pecho (Pectorales)', NULL, 'Barra / Mancuernas', NULL),
  ('Aperturas / Flyes', 'Pecho (Pectorales)', NULL, 'Mancuernas / Máquina Peck Deck / Cables', NULL),
  ('Cruces en Polea', 'Pecho (Pectorales)', NULL, 'Cables', 'Polea alta (pecho bajo), polea media, polea baja (pecho alto).'),
  ('Fondos en Paralelas / Dips', 'Pecho (Pectorales)', NULL, 'Peso corporal', 'Lastrados, en máquina asistida (inclinando el torso hacia adelante).'),
  ('Flexiones / Push-ups', 'Pecho (Pectorales)', NULL, 'Peso corporal', 'Diamante, declinadas (pies elevados), inclinadas (manos elevadas), con palmada.'),
  ('Press de Pecho en Máquina', 'Pecho (Pectorales)', NULL, 'Máquina Sentado', NULL),
  ('Pullover', 'Pecho (Pectorales)', NULL, 'Mancuerna / Pesa Rusa', NULL),
  ('Press de Suelo / Floor Press', 'Pecho (Pectorales)', NULL, 'Barra / Mancuernas', NULL),
  ('Dominadas / Pull-ups', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Peso corporal', 'Agarre prono (abierto), agarre supino (Chin-ups), agarre neutro, lastradas, asistidas en máquina.'),
  ('Jalón al Pecho / Lat Pulldown', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Máquina de cables', 'Agarre ancho, agarre estrecho, barra en V, unilateral.'),
  ('Remo con Barra', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Barra', 'Agarre prono, agarre supino, Remo Pendlay (desde el suelo en cada repetición).'),
  ('Remo con Mancuerna a Una Mano', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Mancuernas / Banco', NULL),
  ('Remo en Máquina Sentado', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Máquina / Cables con agarre V', NULL),
  ('Remo en T / T-Bar Row', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Barra / Máquina', 'Apoyo en pecho o libre.'),
  ('Peso Muerto Tradicional', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Barra', NULL),
  ('Rack Pulls', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Barra sobre soportes', NULL),
  ('Pullover en Polea Alta con Brazo Rígido', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Cables con barra recta o cuerda', NULL),
  ('Hiperextensiones / Extensiones de Espalda', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Silla Romana / Peso Corporal / Lastradas', NULL),
  ('Encogimientos de Hombros / Shrugs', 'Espalda (Dorsales, Romboides, Trapecios)', NULL, 'Barra / Mancuernas / Máquina Smith', NULL),
  ('Press Militar de Pie', 'Hombros (Deltoides)', NULL, 'Barra / Mancuernas / Pesas Rusas', NULL),
  ('Press de Hombros Sentado', 'Hombros (Deltoides)', NULL, 'Mancuernas / Máquina', 'Press Arnold (con rotación).'),
  ('Elevaciones Laterales', 'Hombros (Deltoides)', NULL, 'Mancuernas / Cables / Máquina', 'Sentado, de pie, unilateral en polea.'),
  ('Elevaciones Frontales', 'Hombros (Deltoides)', NULL, 'Mancuernas / Barra / Disco / Cables', NULL),
  ('Pájaros / Elevaciones Posteriores', 'Hombros (Deltoides)', NULL, 'Mancuernas / Máquina Peck Deck Inverso / Cables cruzados', NULL),
  ('Remo al Cuello / Upright Row', 'Hombros (Deltoides)', NULL, 'Barra EZ / Cables / Mancuernas', NULL),
  ('Face Pulls', 'Hombros (Deltoides)', NULL, 'Cables con cuerda', NULL),
  ('Push Press', 'Hombros (Deltoides)', NULL, 'Barra / Mancuernas - usando ligero impulso de piernas', NULL),
  ('Halo con Pesa Rusa', 'Hombros (Deltoides)', NULL, 'Pesa Rusa', NULL),
  ('Curl de Bíceps Tradicional', 'Bíceps y Antebrazos', NULL, 'Barra Recta / Barra EZ / Mancuernas', NULL),
  ('Curl Martillo / Hammer Curl', 'Bíceps y Antebrazos', NULL, 'Mancuernas / Cables con cuerda', 'Frontal o cruzado al pecho.'),
  ('Curl Predicador / Banco Scott', 'Bíceps y Antebrazos', NULL, 'Barra EZ / Mancuernas / Máquina', NULL),
  ('Curl Concentrado', 'Bíceps y Antebrazos', NULL, 'Mancuerna, sentado apoyando el codo en el muslo', NULL),
  ('Curl en Polea Baja', 'Bíceps y Antebrazos', NULL, 'Cables con barra recta o cuerda', NULL),
  ('Curl de Araña / Spider Curl', 'Bíceps y Antebrazos', NULL, 'Barra / Mancuernas en banco inclinado boca abajo', NULL),
  ('Curl Inclinado', 'Bíceps y Antebrazos', NULL, 'Mancuernas en banco a 45 grados', NULL),
  ('Curl Inverso', 'Bíceps y Antebrazos', NULL, 'Barra EZ / Cables - Excelente para el braquiorradial', NULL),
  ('Extensión en Polea Alta / Pushdown', 'Tríceps', NULL, 'Cables', 'Con cuerda, barra recta, barra en V, unilateral con agarre invertido.'),
  ('Press Francés / Skullcrushers', 'Tríceps', NULL, 'Barra EZ / Mancuernas', NULL),
  ('Extensión Tras Nuca', 'Tríceps', NULL, 'Mancuerna a dos manos / Cables / Barra EZ', NULL),
  ('Patada de Burro / Tricep Kickback', 'Tríceps', NULL, 'Mancuerna / Cables', NULL),
  ('Fondos entre Bancos', 'Tríceps', NULL, 'Peso corporal', 'Con discos sobre las piernas para lastre.'),
  ('Press de Banca Agarre Cerrado', 'Tríceps', NULL, 'Barra / Máquina Smith', NULL),
  ('Tate Press', 'Tríceps', NULL, 'Mancuernas', NULL),
  ('JM Press', 'Tríceps', NULL, 'Barra / Máquina Smith', NULL),
  ('Sentadilla Libre / Back Squat', 'Piernas (Cuádriceps)', NULL, 'Barra', 'Barra alta (High bar), barra baja (Low bar), con pausa.'),
  ('Sentadilla Frontal / Front Squat', 'Piernas (Cuádriceps)', NULL, 'Barra', NULL),
  ('Sentadilla Copa / Goblet Squat', 'Piernas (Cuádriceps)', NULL, 'Mancuerna / Pesa Rusa', NULL),
  ('Prensa de Piernas / Leg Press', 'Piernas (Cuádriceps)', NULL, 'Máquina', 'Pies altos (enfoca glúteo/isquio), pies bajos (cuádriceps), pies juntos, postura amplia, unilateral.'),
  ('Sentadilla Búlgara / Bulgarian Split Squat', 'Piernas (Cuádriceps)', NULL, 'Mancuernas / Barra / Peso corporal', NULL),
  ('Zancadas / Lunges', 'Piernas (Cuádriceps)', NULL, 'Mancuernas / Barra / Peso corporal', 'Caminando, estáticas, hacia atrás (reverse lunges), laterales.'),
  ('Extensión de Cuádriceps', 'Piernas (Cuádriceps)', NULL, 'Máquina', NULL),
  ('Sentadilla Hack / Hack Squat', 'Piernas (Cuádriceps)', NULL, 'Máquina / Barra', NULL),
  ('Sentadilla Sissy', 'Piernas (Cuádriceps)', NULL, 'Peso corporal / Máquina específica', NULL),
  ('Subidas al Cajón / Step-ups', 'Piernas (Cuádriceps)', NULL, 'Mancuernas / Barra / Peso corporal', NULL),
  ('Peso Muerto Rumano / RDL', 'Piernas (Isquiosurales / Femorales)', NULL, 'Barra / Mancuernas', NULL),
  ('Peso Muerto con Piernas Rígidas', 'Piernas (Isquiosurales / Femorales)', NULL, 'Barra', NULL),
  ('Curl de Isquios Acostado', 'Piernas (Isquiosurales / Femorales)', NULL, 'Máquina', NULL),
  ('Curl de Isquios Sentado', 'Piernas (Isquiosurales / Femorales)', NULL, 'Máquina', NULL),
  ('Curl de Isquios de Pie', 'Piernas (Isquiosurales / Femorales)', NULL, 'Máquina / Cables', NULL),
  ('Curl Nórdico / Nordic Hamstring Curl', 'Piernas (Isquiosurales / Femorales)', NULL, 'Peso corporal con soporte en los tobillos', NULL),
  ('Buenos Días / Good Mornings', 'Piernas (Isquiosurales / Femorales)', NULL, 'Barra', NULL),
  ('Swing con Pesa Rusa', 'Piernas (Isquiosurales / Femorales)', NULL, 'Pesa Rusa', NULL),
  ('Empuje de Cadera / Hip Thrust', 'Glúteos', NULL, 'Barra / Máquina / Mancuerna', 'Unilateral, con banda elástica de resistencia.'),
  ('Puente de Glúteo / Glute Bridge', 'Glúteos', NULL, 'Peso corporal / Barra', NULL),
  ('Patada de Glúteo / Glute Kickback', 'Glúteos', NULL, 'Cables / Máquina / Peso corporal con banda', NULL),
  ('Abducción de Cadera Sentado', 'Glúteos', NULL, 'Máquina / Bandas', NULL),
  ('Extensiones de Cadera en Polea Baja', 'Glúteos', NULL, 'Cables', NULL),
  ('Sentadilla Sumo', 'Glúteos', NULL, 'Barra / Mancuerna / Pesa Rusa', NULL),
  ('Peso Muerto Sumo', 'Glúteos', NULL, 'Barra', NULL),
  ('Frog Pumps', 'Glúteos', NULL, 'Peso corporal / Mancuerna pequeña', NULL),
  ('Elevación de Talones de Pie', 'Pantorrillas (Gemelos y Sóleo)', NULL, 'Máquina / Barra / Mancuernas - Enfocado en gemelos', NULL),
  ('Elevación de Talones Sentado', 'Pantorrillas (Gemelos y Sóleo)', NULL, 'Máquina / Discos sobre las rodillas - Enfocado en el sóleo', NULL),
  ('Elevación de Talones en Prensa de Piernas', 'Pantorrillas (Gemelos y Sóleo)', NULL, 'Máquina', NULL),
  ('Elevaciones Tipo Burro / Donkey Calf Raises', 'Pantorrillas (Gemelos y Sóleo)', NULL, 'Máquina', NULL),
  ('Elevaciones Unilaterales en Escalón', 'Pantorrillas (Gemelos y Sóleo)', NULL, 'Mancuerna / Peso Corporal', NULL),
  ('Crunches / Encogimientos Abdominales', 'Abdomen y Core', NULL, 'Peso corporal / Máquina', NULL),
  ('Elevación de Piernas Colgado / Hanging Leg Raises', 'Abdomen y Core', NULL, 'Barra de dominadas', 'Rodillas al pecho, piernas estiradas, a los lados (oblicuos).'),
  ('Plancha / Plank', 'Abdomen y Core', NULL, 'Peso corporal', 'Frontal, lateral, con lastre.'),
  ('Rueda Abdominal / Ab Wheel Rollout', 'Abdomen y Core', NULL, 'Rueda / Barra con discos redondos', NULL),
  ('Crunch Inverso', 'Abdomen y Core', NULL, 'Peso corporal, tumbado elevando la pelvis', NULL),
  ('Abdominales en V / V-ups', 'Abdomen y Core', NULL, 'Peso corporal', NULL),
  ('Giros Rusos / Russian Twists', 'Abdomen y Core', NULL, 'Disco / Pesa Rusa / Balón medicinal', NULL),
  ('Leñador / Woodchopper', 'Abdomen y Core', NULL, 'Cables / Mancuerna', NULL),
  ('Toques de Talón / Heel Touches', 'Abdomen y Core', NULL, 'Peso corporal - para oblicuos', NULL),
  ('Escaladores / Mountain Climbers', 'Abdomen y Core', NULL, 'Peso corporal', NULL),
  ('Bicho Muerto / Dead Bug', 'Abdomen y Core', NULL, 'Peso corporal', NULL),
  ('Press Pallof', 'Abdomen y Core', NULL, 'Cables / Bandas elásticas - Trabajo anti-rotacional', NULL),
  ('Abdominales en Polea Alta / Cable Crunches* [cite: 80, 81]', 'Abdomen y Core', NULL, 'Cables con cuerda', NULL),
  ('Cargada de Potencia / Power Clean', '🏋️\u200d♂️ Cuerpo Completo / Halterofilia / Funcional (Opcional para la app)', NULL, 'Barra', NULL),
  ('Arranque / Snatch', '🏋️\u200d♂️ Cuerpo Completo / Halterofilia / Funcional (Opcional para la app)', NULL, 'Barra / Mancuerna / Pesa Rusa', NULL),
  ('Envión / Clean and Jerk', '🏋️\u200d♂️ Cuerpo Completo / Halterofilia / Funcional (Opcional para la app)', NULL, 'Barra', NULL),
  ('Thrusters', '🏋️\u200d♂️ Cuerpo Completo / Halterofilia / Funcional (Opcional para la app)', NULL, 'Barra / Mancuernas', NULL),
  ('Wall Balls / Lanzamiento de Balón', '🏋️\u200d♂️ Cuerpo Completo / Halterofilia / Funcional (Opcional para la app)', NULL, 'Balón medicinal', NULL),
  ('Burpees', '🏋️\u200d♂️ Cuerpo Completo / Halterofilia / Funcional (Opcional para la app)', NULL, 'Peso corporal', NULL);

-- Total: 96 exercises inserted.
